name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: b01080080329/steam-review-api
          stage: main
          yaml: >
            name: steam-review-api-2

            app: dotnet@auto

            options:
              ports: "7192"
              env:
                - name: ConnectionStrings__DbConnection
                  value: ${{ secrets.DB_CONNECTION }}
                - name: GOOGLE_RUNTIME_VERSION
                  value: "9.0.100"
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
